"""add_clima_pluviometrico

Revision ID: 1b6249700f2e
Revises: 
Create Date: 2026-04-05 05:48:39.493803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6249700f2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clima', sa.Column('anotacao_rdo', sa.String(length=5), nullable=True))
    op.add_column('clima', sa.Column('status_pluviometrico', sa.Enum('seco_produtivo', 'seco_improdutivo', 'chuva_produtiva', 'chuva_improdutiva', 'sem_expediente', name='statuspluviometrico'), nullable=True))
    op.alter_column('clima', 'periodo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint('uq_clima_periodo', 'clima', ['obra_id', 'data', 'periodo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clima_periodo', 'clima', type_='unique')
    op.alter_column('clima', 'periodo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('clima', 'status_pluviometrico')
    op.drop_column('clima', 'anotacao_rdo')
    # ### end Alembic commands ###
