"""add_whatsapp_instancias

Revision ID: 1c898ef1db20
Revises: 8c6f0f5c2a91
Create Date: 2026-04-13 14:22:04.404154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c898ef1db20'
down_revision: Union[str, Sequence[str], None] = '8c6f0f5c2a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_instancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome_instancia', sa.String(length=50), nullable=False),
    sa.Column('numero_bot', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('webhook_configurado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_instancia'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_whatsapp_instancias_id'), 'whatsapp_instancias', ['id'], unique=False)
    op.drop_index('ix_alertas_obra_data', table_name='alertas')
    op.drop_index('ix_anotacoes_obra_data', table_name='anotacoes')
    op.drop_index('ix_atividades_obra_status', table_name='atividades')
    op.drop_index('ix_audit_log_obra_data', table_name='audit_log')
    op.drop_index('ix_clima_obra_data', table_name='clima')
    op.drop_index('ix_efetivo_obra_data', table_name='efetivo')
    op.drop_index('ix_equipamentos_obra_data', table_name='equipamentos')
    op.drop_index('ix_fotos_obra_data', table_name='fotos')
    op.drop_index('ix_materiais_obra_data', table_name='materiais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_materiais_obra_data', 'materiais', ['obra_id', 'data'], unique=False)
    op.create_index('ix_fotos_obra_data', 'fotos', ['obra_id', 'data'], unique=False)
    op.create_index('ix_equipamentos_obra_data', 'equipamentos', ['obra_id', 'data'], unique=False)
    op.create_index('ix_efetivo_obra_data', 'efetivo', ['obra_id', 'data'], unique=False)
    op.create_index('ix_clima_obra_data', 'clima', ['obra_id', 'data'], unique=False)
    op.create_index('ix_audit_log_obra_data', 'audit_log', ['obra_id', 'data_ref'], unique=False)
    op.create_index('ix_atividades_obra_status', 'atividades', ['obra_id', 'status'], unique=False)
    op.create_index('ix_anotacoes_obra_data', 'anotacoes', ['obra_id', 'data'], unique=False)
    op.create_index('ix_alertas_obra_data', 'alertas', ['obra_id', 'data', 'resolvido'], unique=False)
    op.drop_index(op.f('ix_whatsapp_instancias_id'), table_name='whatsapp_instancias')
    op.drop_table('whatsapp_instancias')
    # ### end Alembic commands ###
