"""efetivo_tipo_expediente_obra_horarios

Revision ID: b3cfdd8a99bb
Revises: 1b6249700f2e
Create Date: 2026-04-05 06:10:26.718424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cfdd8a99bb'
down_revision: Union[str, Sequence[str], None] = '1b6249700f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Criar o enum antes de usá-lo
    tipoefetivo = sa.Enum('proprio', 'empreiteiro', name='tipoefetivo')
    tipoefetivo.create(op.get_bind(), checkfirst=True)

    # Adicionar coluna nullable primeiro (rows existentes viram 'proprio')
    op.add_column('efetivo', sa.Column('tipo', tipoefetivo, nullable=True))
    op.execute("UPDATE efetivo SET tipo = 'proprio' WHERE tipo IS NULL")
    op.alter_column('efetivo', 'tipo', nullable=False)

    op.alter_column('efetivo', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.add_column('obras', sa.Column('hora_inicio_padrao', sa.String(length=5), nullable=True))
    op.add_column('obras', sa.Column('hora_termino_padrao', sa.String(length=5), nullable=True))
    op.execute("UPDATE obras SET hora_inicio_padrao = '07:00', hora_termino_padrao = '17:00' WHERE hora_inicio_padrao IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obras', 'hora_termino_padrao')
    op.drop_column('obras', 'hora_inicio_padrao')
    op.alter_column('efetivo', 'funcao',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('efetivo', 'tipo')
    # ### end Alembic commands ###
